### ISSUE TITLE
yarn add fails

### ISSUE THREAD

**Issue by logemann** [guardian/lambda-elasticsearch#1]
Hi,

when trying to yarn add your lib, i am getting:
error aws-signed-request@1.0.0: The engine "node" is incompatible with this module. Expected version "0.10.0".

What does this mean?

**Comment by piuccio** [comment]
For some reasons (I can't remember why I did that) [package.json](https://github.com/guardian/lambda-elasticsearch/blob/master/package.json#L15) says that this module works on node 0.10

npm doesn't really enforce that, but apparently yarn complains.

Would you like to send a PR to remove that line?
