### ISSUE TITLE
Docs need updating

### ISSUE THREAD

**Issue by agroves333** [guardian/lambda-elasticsearch#2]
Docs neglect to pass in AWS object as first param and results in an error. 

Should be:

```
var AWS = require('aws-sdk');
var elastic = require('lambda-elasticsearch')(AWS, {
	endpoint: 'your.elasticsearch.es.amazon.com',
	region: 'eu-west-1'
});
```
...

**Comment by piuccio** [comment]
Thanks, I created a PR but I don't have access to the repo anymore, I hope someone at guardian will notice, maybe @Reettaphant ?
